stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/train.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    outs:
      - models/model.pkl