# -*- coding: utf-8 -*-
"""prepare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFXlv-zVOYewAfBRWc891dSj7l2v3juM
"""

import pandas as pd
from sklearn.model_selection import train_test_split

def prepare_data():
    # Загрузка данных
    data = pd.read_csv('data/raw/data.csv', header=None)

    # Названия колонок
    columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
    data.columns = columns

    # Базовая очистка (например, удаление NaN)
    data.dropna(inplace=True)

    # Сплит на train и test
    train, test = train_test_split(data, test_size=0.2, random_state=42)

    # Сохранение обработанных данных
    train.to_csv('data/processed/train.csv', index=False)
    test.to_csv('data/processed/test.csv', index=False)

if __name__ == "__main__":
    prepare_data()