# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFXlv-zVOYewAfBRWc891dSj7l2v3juM
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import joblib
import mlflow

def train_model():
    # Загрузка данных
    train_data = pd.read_csv('data/processed/train.csv')
    test_data = pd.read_csv('data/processed/test.csv')

    # Предположим, что 'class' - это целевая переменная
    X_train = train_data.drop('class', axis=1)
    y_train = train_data['class']

    X_test = test_data.drop('class', axis=1)
    y_test = test_data['class']

    # Логирование параметров и метрик
    mlflow.start_run()

    mlflow.log_param("model", "LogisticRegression")

    # Обучение модели
    model = LogisticRegression()
    model.fit(X_train, y_train)

    # Сохранение модели
    joblib.dump(model, 'model.pkl')

    # Предсказания на тестовом наборе
    predictions = model.predict(X_test)

    # Логирование метрик
    acc = accuracy_score(y_test, predictions)
    mlflow.log_metric("accuracy", acc)

    # Логирование артефактов
    mlflow.log_artifact("model.pkl")

    mlflow.end_run()

if __name__ == "__main__":
    train_model()